<?php
/**
 * @file
 * Install, update and uninstall functions for the mandrill module.
 */

/**
 * Implements hook_enable().
 */
function mandrill_enable() {
  mailsystem_set(array('mandrill_test' => 'MandrillMailSystem'));
}

/**
 * Implements hook_disable().
 */
function mandrill_disable() {
  // Tell mailsystem to remove mandrill and restore to defaults:
  mailsystem_clear(array('mandrill_test' => 'MandrillMailSystem'));
  watchdog('mandrill', 'Mandrill has been disabled.');
}

/**
 * Implements hook_update_last_removed().
 */
function mandrill_update_last_removed() {
  return 7004;
}
